name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # Use Node.js 18+ to prevent crypto issues

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4  # Updated to latest version

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4  # Updated to latest version
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'  # Cache dependencies for faster builds

      - name: Install dependencies
        run: |
          cd backend && npm install || exit 1
          cd ../frontend && npm install || exit 1

      - name: Run backend tests
        run: |
          cd backend && npm test || exit 1

      - name: Build frontend
        run: |
          cd frontend && npm run build || exit 1

      - name: Deploy (optional step)
        run: |
          echo "Deploying app..."
          # Add deployment commands here
